### ISSUE TITLE
Support interface name as arg

### ISSUE THREAD

**Issue by jjcarstens** [nerves-networking/vintage_net_wizard#175]
Right now the wizard only starts on `wlan0` and is hardcoded. We should support the ability to specify the ifname when starting the wizard to decide where it should be started. It would also (potentially) support more than one instance of the wizard

**Comment by mattludwigs** [comment]
As a heads up, I have a branch that is almost done that supports this: https://github.com/nerves-networking/vintage_net_wizard/tree/interface-as-arg. I hope to wrap it up in the next few days.
