### ISSUE TITLE
WiFi connection workflow in the UI

### ISSUE THREAD

**Issue by mattludwigs** [nerves-networking/vintage_net_wizard#44]
Currently when a configuration is applied we assume everything is going to work. However, a new workflow has been suggested:

1. Apply config
1. Show a connecting page/icon
1. Try to connect to the WiFi
1. If successful disconnect and go back to AP mode
1. Tell the client that connection was successful
1. Disconnect

If we cannot connect to the access point after some amount of time, we should handle telling the user that connection did not work.

**Comment by jjcarstens** [comment]
I'm pretty sure we've handled this with #60 and #61, correct?
