### ISSUE TITLE
Allow fill-in configuration in UI

### ISSUE THREAD

**Issue by jjcarstens** [nerves-networking/vintage_net_wizard#54]
Right now you can only add a network configuration from a list of available networks. It would be nice to support adding a config value for a network not available to the device currently for us lazy folk to only setup once

**Comment by fhunleth** [comment]
Definitely want this. This used to exist.

**Comment by jjcarstens** [comment]
NVM. This still exists. The button to add another network was just hidden because the footer was covering it with my smaller window size. Creating a new issue for that
