### ISSUE TITLE
`Scan for Networks` button?

### ISSUE THREAD

**Issue by jjcarstens** [nerves-networking/vintage_net_wizard#90]
Would it be helpful to have a `Scan for Networks` button that calls `VintageNet.scan("wlan0")` on the `/networks` page?

While running wizard on rpi4, it never loads any networks (going on 35 minutes waiting now). Forcing the scan in iex with `VintageNet.scan("wlan0")` does the trick though. This might be a deeper issue into `VintageNet`, but wonder if having that manual button available would be helpful

**Comment by fhunleth** [comment]
`vintage_net_wizard` should call `scan` every 20-30 seconds or so to update its list. @mattludwigs - I was thinking that you did this, but I think it got removed when something didn't work. At any rate, it should be put back?

**Comment by mattludwigs** [comment]
:+1: 

Do we want a button and to control the scan on the backend, or just control the scan on the backend?

**Comment by fhunleth** [comment]
I'd prefer there not to be a button and for it to automatically update.

**Comment by fhunleth** [comment]
Fixed by 44545b400a0dee556188fabd55e5db2f8c3122bf.
