### ISSUE TITLE
Exit wizard on inactivity

### ISSUE THREAD

**Issue by fhunleth** [nerves-networking/vintage_net_wizard#98]
It's possible for the wizard to be entered accidentally or for someone to start it and change their mind. To avoid devices being in the wizard indefinitely when they might have a valid configuration, exit the wizard after a timeout. 

I'm not sure what a good default timeout is, but 10 minutes seems reasonable. This should be configurable.

**Comment by jjcarstens** [comment]
Is this a behavior we want VintageNetWizard to handle? Or is it more useful to work in conjunction with #122 and send notifications of inactivity and let the calling app decide what to do?

I think just holding in the wizard and shutting it down after inactivity would be fine, but thought I'd bring up just in case

**Comment by lucaong** [comment]
One good reason to do this within VintageNetWizard is that, currently, when the AP goes down to check for connectivity after setting credentials, the user's machine might connect to other available WiFi networks. In that case, even when the checks are successful, the user never gets to see the "complete" page, and the device will stay in AP mode indefinitely.

Expert users would know that they need to reconnect manually to the AP, but ideally the AP could automatically shut down after a timeout. In this specific case, when checks were successful, even 1 minute timeout would probably be enough: basically one would just wait long enough to give the user a chance to see the success page in case they're still connected to the AP.

This could even make the "complete" button redundant, as the complete page could just say something of the sort "all configured successfully, the AP will automatically shut down in 1 minute and the device will be ready to connect".
